server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/slmanju/microservices-blog
#          default-label: config-server
          searchPaths: configurations
          skipSslValidation: true

#server:
#  port: 8888
#
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: file:///home/manjula/config-repo


